on: push

name: CI

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make deps
      - run: make lint
      - run: make codegen.dts
      - name: Ensure type definition is up-to-date
        run: |
          git add --intent-to-add .
          git diff --exit-code --stat
